package org.mortgages;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Brama implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean otwarte;

   public Brama()
   {
   }

   public java.lang.Boolean getOtwarte()
   {
      return this.otwarte;
   }

   public void setOtwarte(java.lang.Boolean otwarte)
   {
      this.otwarte = otwarte;
   }

   public Brama(java.lang.Boolean otwarte)
   {
      this.otwarte = otwarte;
   }

}