package org.mortgages;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CzujnikPodjazdu implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean wykrytyRuch;

   public CzujnikPodjazdu()
   {
   }

   public java.lang.Boolean getWykrytyRuch()
   {
      return this.wykrytyRuch;
   }

   public void setWykrytyRuch(java.lang.Boolean wykrytyRuch)
   {
      this.wykrytyRuch = wykrytyRuch;
   }

   public CzujnikPodjazdu(java.lang.Boolean wykrytyRuch)
   {
      this.wykrytyRuch = wykrytyRuch;
   }

}