package org.mortgages;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CzujnikRuchu implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean ruchWykryty;

   public CzujnikRuchu()
   {
   }

   public java.lang.Boolean getRuchWykryty()
   {
      return this.ruchWykryty;
   }

   public void setRuchWykryty(java.lang.Boolean ruchWykryty)
   {
      this.ruchWykryty = ruchWykryty;
   }

   public CzujnikRuchu(java.lang.Boolean ruchWykryty)
   {
      this.ruchWykryty = ruchWykryty;
   }

}