package org.mortgages;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CzujnikPogody implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.math.BigDecimal obecnaTemperatura;
   private java.math.BigDecimal prognozowanaTemperatura;

   public CzujnikPogody()
   {
   }

   public java.math.BigDecimal getObecnaTemperatura()
   {
      return this.obecnaTemperatura;
   }

   public void setObecnaTemperatura(java.math.BigDecimal obecnaTemperatura)
   {
      this.obecnaTemperatura = obecnaTemperatura;
   }

   public java.math.BigDecimal getPrognozowanaTemperatura()
   {
      return this.prognozowanaTemperatura;
   }

   public void setPrognozowanaTemperatura(
         java.math.BigDecimal prognozowanaTemperatura)
   {
      this.prognozowanaTemperatura = prognozowanaTemperatura;
   }

   public CzujnikPogody(java.math.BigDecimal obecnaTemperatura,
         java.math.BigDecimal prognozowanaTemperatura)
   {
      this.obecnaTemperatura = obecnaTemperatura;
      this.prognozowanaTemperatura = prognozowanaTemperatura;
   }

}