package org.mortgages;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Pokoj implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private org.mortgages.CzujnikRuchu czujnikRuchu;
   private org.mortgages.Swiatlo swiatlo;

   private org.mortgages.UrzadzenieMultimedialne urzadzenieMultimedialne;

   public Pokoj()
   {
   }

   public org.mortgages.CzujnikRuchu getCzujnikRuchu()
   {
      return this.czujnikRuchu;
   }

   public void setCzujnikRuchu(org.mortgages.CzujnikRuchu czujnikRuchu)
   {
      this.czujnikRuchu = czujnikRuchu;
   }

   public org.mortgages.Swiatlo getSwiatlo()
   {
      return this.swiatlo;
   }

   public void setSwiatlo(org.mortgages.Swiatlo swiatlo)
   {
      this.swiatlo = swiatlo;
   }

   public org.mortgages.UrzadzenieMultimedialne getUrzadzenieMultimedialne()
   {
      return this.urzadzenieMultimedialne;
   }

   public void setUrzadzenieMultimedialne(
         org.mortgages.UrzadzenieMultimedialne urzadzenieMultimedialne)
   {
      this.urzadzenieMultimedialne = urzadzenieMultimedialne;
   }

   public Pokoj(org.mortgages.CzujnikRuchu czujnikRuchu,
         org.mortgages.Swiatlo swiatlo,
         org.mortgages.UrzadzenieMultimedialne urzadzenieMultimedialne)
   {
      this.czujnikRuchu = czujnikRuchu;
      this.swiatlo = swiatlo;
      this.urzadzenieMultimedialne = urzadzenieMultimedialne;
   }

}