package org.mortgages;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Powiadomienie implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String wiadomosc;

   public Powiadomienie()
   {
   }

   public java.lang.String getWiadomosc()
   {
      return this.wiadomosc;
   }

   public void setWiadomosc(java.lang.String wiadomosc)
   {
      this.wiadomosc = wiadomosc;
   }

   public Powiadomienie(java.lang.String wiadomosc)
   {
      this.wiadomosc = wiadomosc;
   }

}