package org.mortgages;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Termometr implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.math.BigDecimal temperatura;

   private java.lang.String poraRoku;

   public Termometr()
   {
   }

   public java.math.BigDecimal getTemperatura()
   {
      return this.temperatura;
   }

   public void setTemperatura(java.math.BigDecimal temperatura)
   {
      this.temperatura = temperatura;
   }

   public java.lang.String getPoraRoku()
   {
      return this.poraRoku;
   }

   public void setPoraRoku(java.lang.String poraRoku)
   {
      this.poraRoku = poraRoku;
   }

   public Termometr(java.math.BigDecimal temperatura, java.lang.String poraRoku)
   {
      this.temperatura = temperatura;
      this.poraRoku = poraRoku;
   }

}