package org.mortgages;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Termostat implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean wlaczony;

   private java.math.BigDecimal temperatura;

   public Termostat()
   {
   }

   public java.lang.Boolean getWlaczony()
   {
      return this.wlaczony;
   }

   public void setWlaczony(java.lang.Boolean wlaczony)
   {
      this.wlaczony = wlaczony;
   }

   public java.math.BigDecimal getTemperatura()
   {
      return this.temperatura;
   }

   public void setTemperatura(java.math.BigDecimal temperatura)
   {
      this.temperatura = temperatura;
   }

   public Termostat(java.lang.Boolean wlaczony, java.math.BigDecimal temperatura)
   {
      this.wlaczony = wlaczony;
      this.temperatura = temperatura;
   }

}