package org.mortgages;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class UrzadzenieMultimedialne implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean wlaczone;

   public UrzadzenieMultimedialne()
   {
   }

   public java.lang.Boolean getWlaczone()
   {
      return this.wlaczone;
   }

   public void setWlaczone(java.lang.Boolean wlaczone)
   {
      this.wlaczone = wlaczone;
   }

   public UrzadzenieMultimedialne(java.lang.Boolean wlaczone)
   {
      this.wlaczone = wlaczone;
   }

}