package org.mortgages;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Zegar implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.Date obecnyCzas;

   public Zegar()
   {
   }

   public java.util.Date getObecnyCzas()
   {
      return this.obecnyCzas;
   }

   public void setObecnyCzas(java.util.Date obecnyCzas)
   {
      this.obecnyCzas = obecnyCzas;
   }

   public Zegar(java.util.Date obecnyCzas)
   {
      this.obecnyCzas = obecnyCzas;
   }

}